add preprocessing

diff --git a/.local/bin/ffn b/.local/bin/ffn
--- a/.local/bin/ffn
+++ b/.local/bin/ffn
@@ -2,8 +2,9 @@
 # Program:
 # 	* rename file while removing [:punct:], replace [:upper:] with
 #	  [:lower:], replace "${sep}" with '_'
-# 	* while given '-d' , do not rename file, only print new
+# 	* while given '-d', do not rename file, only print new
 # 	  file name
+# 	* while given '-e <arg>', file name is preprocessed by sed -e <arg>...
 # Dependency:
 # 	* nil
 # Author:
@@ -25,6 +26,7 @@ Usage:
 
 Options:
   -d                   Perform a 'dry run'. Do not actually rename file.
+  -e <arg>             Preprocessed file name by sed -e <arg>...
   -h                   Show this message and exit.
 
 EOF
@@ -40,6 +42,16 @@ process_file()
 	if [ -z "${file}" ] || [ -z "${dir}" ] || [ -z "${base}" ]; then
 		printf '%s: error parsing file: %s\n' "${progname}" "${file}" 1>&2
 		return 1
+	fi
+
+	if [ "${e_flag}" = '1' ]; then
+		base="$(
+			printf '%s' "${base}" | sed ${e_string}
+		)"
+		if [ "$?" != '0' ]; then
+			printf '%s: error executing sed %s\n' "${progname}" \
+			    "${e_string}" 1>&2
+		fi
 	fi
 
 	case "${base}" in
@@ -95,14 +107,20 @@ process_file()
 
 readonly progname="$(basename "$0")"
 d_flag='0'
+e_flag='0'
+e_string=''
 total_file_cnt='0'
 success_file_cnt='0'
 clean_file_cnt='0'
 
-while getopts 'dh' opt; do
+while getopts 'de:h' opt; do
 	case "${opt}" in
 	'd')
-		readonly d_flag='1'
+		d_flag='1'
+		;;
+	'e')
+		e_flag='1'
+		e_string="${e_string} -e '${OPTARG}'"
 		;;
 	'h')
 		help_msg
